sudo: false
language: python
python:
  - "3.6"
addons:
  postgresql: "9.4"
before_script:
  - createdb braingames_db
install:
  - pip install tox
env:
  - TOX_ENV=flake8
  - TOX_ENV=tests
script:
  - tox -e $TOX_ENV
